//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlagSync.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlagSync.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionGridViewColumnText {
            get {
                return ResourceManager.GetString("ActionGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application needs to restart..
        /// </summary>
        public static string ApplicationRestartMessageBoxCaption {
            get {
                return ResourceManager.GetString("ApplicationRestartMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application needs to restart. Do you wish to continue?.
        /// </summary>
        public static string ApplicationRestartMessageBoxText {
            get {
                return ResourceManager.GetString("ApplicationRestartMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AuthorTextBlockText {
            get {
                return ResourceManager.GetString("AuthorTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string BackupModeRadioButtonText {
            get {
                return ResourceManager.GetString("BackupModeRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        public static string CommonSettingsGroupBoxText {
            get {
                return ResourceManager.GetString("CommonSettingsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueString {
            get {
                return ResourceManager.GetString("ContinueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing jobs..
        /// </summary>
        public static string ContinuingJobsMessage {
            get {
                return ResourceManager.GetString("ContinuingJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanelGroupBoxText {
            get {
                return ResourceManager.GetString("ControlPanelGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Error.
        /// </summary>
        public static string CopyErrorString {
            get {
                return ResourceManager.GetString("CopyErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting files....
        /// </summary>
        public static string CountingFilesMessage {
            get {
                return ResourceManager.GetString("CountingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.
        /// </summary>
        public static string CreatingString {
            get {
                return ResourceManager.GetString("CreatingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Job.
        /// </summary>
        public static string CurrentJobGroupBoxText {
            get {
                return ResourceManager.GetString("CurrentJobGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current progress:.
        /// </summary>
        public static string CurrentProgressText {
            get {
                return ResourceManager.GetString("CurrentProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Job.
        /// </summary>
        public static string DeleteJobButtonText {
            get {
                return ResourceManager.GetString("DeleteJobButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        public static string DeletingString {
            get {
                return ResourceManager.GetString("DeletingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Error.
        /// </summary>
        public static string DeletionErrorString {
            get {
                return ResourceManager.GetString("DeletionErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory A.
        /// </summary>
        public static string DirectoryAButtonText {
            get {
                return ResourceManager.GetString("DirectoryAButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory A doesn&apos;t exist!.
        /// </summary>
        public static string DirectoryADoesntExistMessage {
            get {
                return ResourceManager.GetString("DirectoryADoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory A:.
        /// </summary>
        public static string DirectoryATextBlockText {
            get {
                return ResourceManager.GetString("DirectoryATextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory B.
        /// </summary>
        public static string DirectoryBButtonText {
            get {
                return ResourceManager.GetString("DirectoryBButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory B doesn&apos;t exist!.
        /// </summary>
        public static string DirectoryBDoesntExistMessage {
            get {
                return ResourceManager.GetString("DirectoryBDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory B:.
        /// </summary>
        public static string DirectoryBTextBlockText {
            get {
                return ResourceManager.GetString("DirectoryBTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string DirectoryButtonText {
            get {
                return ResourceManager.GetString("DirectoryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory doesn&apos;t exist!.
        /// </summary>
        public static string DirectoryDoesntExistMessage {
            get {
                return ResourceManager.GetString("DirectoryDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string DirectoryString {
            get {
                return ResourceManager.GetString("DirectoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time:.
        /// </summary>
        public static string ElapsedTimeMessage {
            get {
                return ResourceManager.GetString("ElapsedTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Scheduling.
        /// </summary>
        public static string EnableSchedulingGroupboxHeaderText {
            get {
                return ResourceManager.GetString("EnableSchedulingGroupboxHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishString {
            get {
                return ResourceManager.GetString("EnglishString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorString {
            get {
                return ResourceManager.GetString("ErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMenuItemText {
            get {
                return ResourceManager.GetString("ExitMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filesize.
        /// </summary>
        public static string FileSizeGridViewColumnText {
            get {
                return ResourceManager.GetString("FileSizeGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileString {
            get {
                return ResourceManager.GetString("FileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished all jobs..
        /// </summary>
        public static string FinishedAllJobsMessage {
            get {
                return ResourceManager.GetString("FinishedAllJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished file counting..
        /// </summary>
        public static string FinishedFileCountingMessage {
            get {
                return ResourceManager.GetString("FinishedFileCountingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished job:.
        /// </summary>
        public static string FinishedJobMessage {
            get {
                return ResourceManager.GetString("FinishedJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP-Address cannot be empty!.
        /// </summary>
        public static string FTPAddressCantBeEmptyMessage {
            get {
                return ResourceManager.GetString("FTPAddressCantBeEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP-Address has the wrong format!.
        /// </summary>
        public static string FTPAdressWrongFormatMessage {
            get {
                return ResourceManager.GetString("FTPAdressWrongFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP-Server Address:.
        /// </summary>
        public static string FtpServerAddressJobSettingsTextBlockText {
            get {
                return ResourceManager.GetString("FtpServerAddressJobSettingsTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP backup.
        /// </summary>
        public static string FtpServerBackupString {
            get {
                return ResourceManager.GetString("FtpServerBackupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string FtpServerPasswordJobSettingsTextBlockText {
            get {
                return ResourceManager.GetString("FtpServerPasswordJobSettingsTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Proxy Server.
        /// </summary>
        public static string FtpServerProxySettingsGroupBoxText {
            get {
                return ResourceManager.GetString("FtpServerProxySettingsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP Synchronization.
        /// </summary>
        public static string FtpServerSynchronizationString {
            get {
                return ResourceManager.GetString("FtpServerSynchronizationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string FtpServerUserNameJobSettingsTextBlockText {
            get {
                return ResourceManager.GetString("FtpServerUserNameJobSettingsTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FTP.
        /// </summary>
        public static string FTPString {
            get {
                return ResourceManager.GetString("FTPString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string GermanString {
            get {
                return ResourceManager.GetString("GermanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string HelpMenuItemText {
            get {
                return ResourceManager.GetString("HelpMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string iTunesErrorMessageBoxCaption {
            get {
                return ResourceManager.GetString("iTunesErrorMessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open iTunes first!.
        /// </summary>
        public static string iTunesErrorMessageBoxText {
            get {
                return ResourceManager.GetString("iTunesErrorMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes.
        /// </summary>
        public static string iTunesString {
            get {
                return ResourceManager.GetString("iTunesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageMenuItemText {
            get {
                return ResourceManager.GetString("LanguageMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ListBoxItemJobNameText {
            get {
                return ResourceManager.GetString("ListBoxItemJobNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string ListBoxItemJobTypeText {
            get {
                return ResourceManager.GetString("ListBoxItemJobTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Jobs.
        /// </summary>
        public static string LoadJobsButtonText {
            get {
                return ResourceManager.GetString("LoadJobsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading the jobs! Maybe the file is corrupt..
        /// </summary>
        public static string LoadSettingsErrorMessage {
            get {
                return ResourceManager.GetString("LoadSettingsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string LoadString {
            get {
                return ResourceManager.GetString("LoadString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local backup.
        /// </summary>
        public static string LocalBackupString {
            get {
                return ResourceManager.GetString("LocalBackupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string LocalString {
            get {
                return ResourceManager.GetString("LocalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local synchronization.
        /// </summary>
        public static string LocalSynchronizationString {
            get {
                return ResourceManager.GetString("LocalSynchronizationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string LogTabItemText {
            get {
                return ResourceManager.GetString("LogTabItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        public static string ModeTextBlockText {
            get {
                return ResourceManager.GetString("ModeTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying.
        /// </summary>
        public static string ModifyingString {
            get {
                return ResourceManager.GetString("ModifyingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field can&apos;t be empty!.
        /// </summary>
        public static string NameFieldCantBeEmptyMessage {
            get {
                return ResourceManager.GetString("NameFieldCantBeEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameJobSettingsTextBlockText {
            get {
                return ResourceManager.GetString("NameJobSettingsTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameTextBlockText {
            get {
                return ResourceManager.GetString("NameTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        public static string NewJobButtonText {
            get {
                return ResourceManager.GetString("NewJobButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        public static string NewJobString {
            get {
                return ResourceManager.GetString("NewJobString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewString {
            get {
                return ResourceManager.GetString("NewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active job.
        /// </summary>
        public static string NoActiveJobText {
            get {
                return ResourceManager.GetString("NoActiveJobText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused jobs..
        /// </summary>
        public static string PausedJobsMessage {
            get {
                return ResourceManager.GetString("PausedJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string PauseString {
            get {
                return ResourceManager.GetString("PauseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist:.
        /// </summary>
        public static string PlaylistJobSettingTextBlockText {
            get {
                return ResourceManager.GetString("PlaylistJobSettingTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string PreviewButtonText {
            get {
                return ResourceManager.GetString("PreviewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string ProgramMenuItemText {
            get {
                return ResourceManager.GetString("ProgramMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string ProgressGridViewColumnText {
            get {
                return ResourceManager.GetString("ProgressGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string ProxyAddressTextBlockText {
            get {
                return ResourceManager.GetString("ProxyAddressTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string ProxyPasswordTextBlockText {
            get {
                return ResourceManager.GetString("ProxyPasswordTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string ProxyPortTextBlockText {
            get {
                return ResourceManager.GetString("ProxyPortTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string ProxyUserNameTextBlockText {
            get {
                return ResourceManager.GetString("ProxyUserNameTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Jobs.
        /// </summary>
        public static string SaveJobsButtonText {
            get {
                return ResourceManager.GetString("SaveJobsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveString {
            get {
                return ResourceManager.GetString("SaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to select a playlist!.
        /// </summary>
        public static string SelectPlaylistErrorMessage {
            get {
                return ResourceManager.GetString("SelectPlaylistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTabItemText {
            get {
                return ResourceManager.GetString("SettingsTabItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SourceGridViewColumnText {
            get {
                return ResourceManager.GetString("SourceGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting job:.
        /// </summary>
        public static string StartingJobMessage {
            get {
                return ResourceManager.GetString("StartingJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting jobs..
        /// </summary>
        public static string StartingJobsMessage {
            get {
                return ResourceManager.GetString("StartingJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string StopButtonText {
            get {
                return ResourceManager.GetString("StopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped all jobs..
        /// </summary>
        public static string StoppedAllJobsMessage {
            get {
                return ResourceManager.GetString("StoppedAllJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sychronization.
        /// </summary>
        public static string SyncModeRadioButtonText {
            get {
                return ResourceManager.GetString("SyncModeRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory.
        /// </summary>
        public static string TargetGridViewColumnText {
            get {
                return ResourceManager.GetString("TargetGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string TestConnectionButtonText {
            get {
                return ResourceManager.GetString("TestConnectionButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel:.
        /// </summary>
        public static string TitleTextBlockText {
            get {
                return ResourceManager.GetString("TitleTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total progress:.
        /// </summary>
        public static string TotalProgressText {
            get {
                return ResourceManager.GetString("TotalProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeGridViewColumnText {
            get {
                return ResourceManager.GetString("TypeGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A newer version is available!.
        /// </summary>
        public static string UpdateAvailableText {
            get {
                return ResourceManager.GetString("UpdateAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string VersionTextBlockText {
            get {
                return ResourceManager.GetString("VersionTextBlockText", resourceCulture);
            }
        }
    }
}
