//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlagSync.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlagSync.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutString {
            get {
                return ResourceManager.GetString("AboutString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ActionGridViewColumnText {
            get {
                return ResourceManager.GetString("ActionGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        internal static string AuthorTextBlockText {
            get {
                return ResourceManager.GetString("AuthorTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string BackupModeRadioButtonText {
            get {
                return ResourceManager.GetString("BackupModeRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Settings.
        /// </summary>
        internal static string CommonSettingsGroupBoxText {
            get {
                return ResourceManager.GetString("CommonSettingsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ContinueString {
            get {
                return ResourceManager.GetString("ContinueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuing jobs..
        /// </summary>
        internal static string ContinuingJobsMessage {
            get {
                return ResourceManager.GetString("ContinuingJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        internal static string ControlPanelGroupBoxText {
            get {
                return ResourceManager.GetString("ControlPanelGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Error.
        /// </summary>
        internal static string CopyErrorString {
            get {
                return ResourceManager.GetString("CopyErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting files....
        /// </summary>
        internal static string CountingFilesMessage {
            get {
                return ResourceManager.GetString("CountingFilesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.
        /// </summary>
        internal static string CreatingString {
            get {
                return ResourceManager.GetString("CreatingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Job.
        /// </summary>
        internal static string CurrentJobGroupBoxText {
            get {
                return ResourceManager.GetString("CurrentJobGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Job.
        /// </summary>
        internal static string DeleteJobButtonText {
            get {
                return ResourceManager.GetString("DeleteJobButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting.
        /// </summary>
        internal static string DeletingString {
            get {
                return ResourceManager.GetString("DeletingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Error.
        /// </summary>
        internal static string DeletionErrorString {
            get {
                return ResourceManager.GetString("DeletionErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory A.
        /// </summary>
        internal static string DirectoryAButtonText {
            get {
                return ResourceManager.GetString("DirectoryAButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory A doesn&apos;t exist!.
        /// </summary>
        internal static string DirectoryADoesntExistMessage {
            get {
                return ResourceManager.GetString("DirectoryADoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory A:.
        /// </summary>
        internal static string DirectoryATextBlockText {
            get {
                return ResourceManager.GetString("DirectoryATextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory B.
        /// </summary>
        internal static string DirectoryBButtonText {
            get {
                return ResourceManager.GetString("DirectoryBButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory B doesn&apos;t exist!.
        /// </summary>
        internal static string DirectoryBDoesntExistMessage {
            get {
                return ResourceManager.GetString("DirectoryBDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory B:.
        /// </summary>
        internal static string DirectoryBTextBlockText {
            get {
                return ResourceManager.GetString("DirectoryBTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory doesn&apos;t exist!.
        /// </summary>
        internal static string DirectoryDoesntExistMessage {
            get {
                return ResourceManager.GetString("DirectoryDoesntExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string DirectoryString {
            get {
                return ResourceManager.GetString("DirectoryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time:.
        /// </summary>
        internal static string ElapsedTimeMessage {
            get {
                return ResourceManager.GetString("ElapsedTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishString {
            get {
                return ResourceManager.GetString("EnglishString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitMenuItemText {
            get {
                return ResourceManager.GetString("ExitMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileString {
            get {
                return ResourceManager.GetString("FileString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished all jobs..
        /// </summary>
        internal static string FinishedAllJobsMessage {
            get {
                return ResourceManager.GetString("FinishedAllJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished file counting..
        /// </summary>
        internal static string FinishedFileCountingMessage {
            get {
                return ResourceManager.GetString("FinishedFileCountingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished job:.
        /// </summary>
        internal static string FinishedJobMessage {
            get {
                return ResourceManager.GetString("FinishedJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string GermanString {
            get {
                return ResourceManager.GetString("GermanString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string HelpMenuItemText {
            get {
                return ResourceManager.GetString("HelpMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageMenuItemText {
            get {
                return ResourceManager.GetString("LanguageMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Jobs.
        /// </summary>
        internal static string LoadJobsButtonText {
            get {
                return ResourceManager.GetString("LoadJobsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string LogTabItemText {
            get {
                return ResourceManager.GetString("LogTabItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode:.
        /// </summary>
        internal static string ModeTextBlockText {
            get {
                return ResourceManager.GetString("ModeTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying.
        /// </summary>
        internal static string ModifyingString {
            get {
                return ResourceManager.GetString("ModifyingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name field can&apos;t be empty!.
        /// </summary>
        internal static string NameFieldCantBeEmptyMessage {
            get {
                return ResourceManager.GetString("NameFieldCantBeEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string NameTextBlockText {
            get {
                return ResourceManager.GetString("NameTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        internal static string NewJobButtonText {
            get {
                return ResourceManager.GetString("NewJobButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Job.
        /// </summary>
        internal static string NewJobString {
            get {
                return ResourceManager.GetString("NewJobString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused jobs..
        /// </summary>
        internal static string PausedJobsMessage {
            get {
                return ResourceManager.GetString("PausedJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string PauseString {
            get {
                return ResourceManager.GetString("PauseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string PreviewButtonText {
            get {
                return ResourceManager.GetString("PreviewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string ProgramMenuItemText {
            get {
                return ResourceManager.GetString("ProgramMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string ProgressGridViewColumnText {
            get {
                return ResourceManager.GetString("ProgressGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Jobs.
        /// </summary>
        internal static string SaveJobsButtonText {
            get {
                return ResourceManager.GetString("SaveJobsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTabItemText {
            get {
                return ResourceManager.GetString("SettingsTabItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SourceGridViewColumnText {
            get {
                return ResourceManager.GetString("SourceGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartButtonText {
            get {
                return ResourceManager.GetString("StartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting job:.
        /// </summary>
        internal static string StartingJobMessage {
            get {
                return ResourceManager.GetString("StartingJobMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting jobs..
        /// </summary>
        internal static string StartingJobsMessage {
            get {
                return ResourceManager.GetString("StartingJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopButtonText {
            get {
                return ResourceManager.GetString("StopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped all jobs..
        /// </summary>
        internal static string StoppedAllJobsMessage {
            get {
                return ResourceManager.GetString("StoppedAllJobsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sychronization.
        /// </summary>
        internal static string SyncModeRadioButtonText {
            get {
                return ResourceManager.GetString("SyncModeRadioButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target directory.
        /// </summary>
        internal static string TargetGridViewColumnText {
            get {
                return ResourceManager.GetString("TargetGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel:.
        /// </summary>
        internal static string TitleTextBlockText {
            get {
                return ResourceManager.GetString("TitleTextBlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string TypeGridViewColumnText {
            get {
                return ResourceManager.GetString("TypeGridViewColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string VersionTextBlockText {
            get {
                return ResourceManager.GetString("VersionTextBlockText", resourceCulture);
            }
        }
    }
}
